/* ###*B*###
 * ERIKA Enterprise - a tiny RTOS for small microcontrollers
 *
 * Copyright (C) 2002-2011  Evidence Srl
 *
 * This file is part of ERIKA Enterprise.
 *
 * ERIKA Enterprise is free software; you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * version 2 as published by the Free Software Foundation, 
 * (with a special exception described below).
 *
 * Linking this code statically or dynamically with other modules is
 * making a combined work based on this code.  Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * As a special exception, the copyright holders of this library give you
 * permission to link this code with independent modules to produce an
 * executable, regardless of the license terms of these independent
 * modules, and to copy and distribute the resulting executable under
 * terms of your choice, provided that you also meet, for each linked
 * independent module, the terms and conditions of the license of that
 * module.  An independent module is a module which is not derived from
 * or based on this library.  If you modify this code, you may extend
 * this exception to your version of the code, but you are not
 * obligated to do so.  If you do not wish to do so, delete this
 * exception statement from your version.
 *
 * ERIKA Enterprise is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details.
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with ERIKA Enterprise; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301 USA.
 * ###*E*### */

/** 
	@file ee_utils.c
	@brief Functions to initialize the RTOS services
	@author Gianluca Franchino
	@author Giuseppe Serano
	@date 2011
*/ 

#include "ee_internal.h"
#include "ee_irq.h"
#include "cpu/cortex_mx/inc/ee_nvic.h"

#ifdef __USE_SVC__
extern void EE_set_sv_call_pri(void);
#endif

extern void EE_set_switch_context_pri(void);

/* Function used to calculate the initialize the system */
void EE_system_init(void)
{
#ifdef __USE_SVC__
	/* 
	 * Set the priority of SVCall to the minimum one
	 * SVCall is the software interrupt used for context switch
	 */
	EE_set_sv_call_pri();
#endif

	/* 
	 * Set the priority of PendSV to the minimum one
	 * PendSV is the software interrupt used for context switch
	 */
	EE_set_switch_context_pri();

#ifdef EE_CORTEX_MX_SYSTICK_ISR
#ifdef EE_CORTEX_MX_SYSTICK_ISR_PRI
	NVIC_SYS_PRI3_R |= (
	  EE_CORTEX_MX_SYSTICK_ISR_PRI << NVIC_SYS_PRI3_TICK_S
	);
#endif
#endif

#ifdef EE_CORTEX_MX_GPIO_A_ISR
#ifdef EE_CORTEX_MX_GPIO_A_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_A_INT_NUM, EE_CORTEX_MX_GPIO_A_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_A_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_A_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_A_ISR */


#ifdef EE_CORTEX_MX_GPIO_B_ISR
#ifdef EE_CORTEX_MX_GPIO_B_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_B_INT_NUM, EE_CORTEX_MX_GPIO_B_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_B_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_B_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_B_ISR */


#ifdef EE_CORTEX_MX_GPIO_C_ISR
#ifdef EE_CORTEX_MX_GPIO_C_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_C_INT_NUM, EE_CORTEX_MX_GPIO_C_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_C_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_C_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_C_ISR */


#ifdef EE_CORTEX_MX_GPIO_D_ISR
#ifdef EE_CORTEX_MX_GPIO_D_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_D_INT_NUM, EE_CORTEX_MX_GPIO_D_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_D_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_D_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_D_ISR */


#ifdef EE_CORTEX_MX_GPIO_E_ISR
#ifdef EE_CORTEX_MX_GPIO_E_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_E_INT_NUM, EE_CORTEX_MX_GPIO_E_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_E_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_E_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_E_ISR */

#ifdef EE_CORTEX_MX_GPIO_F_ISR
#ifdef EE_CORTEX_MX_GPIO_F_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_F_INT_NUM, EE_CORTEX_MX_GPIO_F_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_F_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_F_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_F_ISR */


#ifdef EE_CORTEX_MX_GPIO_G_ISR
#ifdef EE_CORTEX_MX_GPIO_G_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_G_INT_NUM, EE_CORTEX_MX_GPIO_G_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_G_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_G_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_G_ISR */


#ifdef EE_CORTEX_MX_GPIO_H_ISR
#ifdef EE_CORTEX_MX_GPIO_H_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_H_INT_NUM, EE_CORTEX_MX_GPIO_H_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_H_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_H_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_H_ISR */


#ifdef EE_CORTEX_MX_GPIO_J_ISR
#ifdef EE_CORTEX_MX_GPIO_J_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_J_INT_NUM, EE_CORTEX_MX_GPIO_J_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_J_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_J_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_J_ISR */


#ifdef EE_CORTEX_MX_GPIO_K_ISR
#ifdef EE_CORTEX_MX_GPIO_K_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_K_INT_NUM, EE_CORTEX_MX_GPIO_K_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_K_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_K_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_K_ISR */


#ifdef EE_CORTEX_MX_GPIO_L_ISR
#ifdef EE_CORTEX_MX_GPIO_L_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_L_INT_NUM, EE_CORTEX_MX_GPIO_L_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_L_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_L_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_L_ISR */


#ifdef EE_CORTEX_MX_GPIO_M_ISR
#ifdef EE_CORTEX_MX_GPIO_M_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_M_INT_NUM, EE_CORTEX_MX_GPIO_M_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_M_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_M_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_M_ISR */


#ifdef EE_CORTEX_MX_GPIO_N_ISR
#ifdef EE_CORTEX_MX_GPIO_N_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_N_INT_NUM, EE_CORTEX_MX_GPIO_N_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_N_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_N_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_N_ISR */


#ifdef EE_CORTEX_MX_GPIO_P0_ISR
#ifdef EE_CORTEX_MX_GPIO_P0_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_P0_INT_NUM, EE_CORTEX_MX_GPIO_P0_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_P0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_P0_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_P0_ISR */


#ifdef EE_CORTEX_MX_GPIO_P1_ISR
#ifdef EE_CORTEX_MX_GPIO_P1_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_P1_INT_NUM, EE_CORTEX_MX_GPIO_P1_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_P1_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_P1_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_P1_ISR */


#ifdef EE_CORTEX_MX_GPIO_P2_ISR
#ifdef EE_CORTEX_MX_GPIO_P2_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_P2_INT_NUM, EE_CORTEX_MX_GPIO_P2_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_P2_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_P2_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_P2_ISR */


#ifdef EE_CORTEX_MX_GPIO_P3_ISR
#ifdef EE_CORTEX_MX_GPIO_P3_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_P3_INT_NUM, EE_CORTEX_MX_GPIO_P3_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_P3_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_P3_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_P3_ISR */


#ifdef EE_CORTEX_MX_GPIO_P4_ISR
#ifdef EE_CORTEX_MX_GPIO_P4_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_P4_INT_NUM, EE_CORTEX_MX_GPIO_P4_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_P4_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_P4_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_P4_ISR */


#ifdef EE_CORTEX_MX_GPIO_P5_ISR
#ifdef EE_CORTEX_MX_GPIO_P5_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_P5_INT_NUM, EE_CORTEX_MX_GPIO_P5_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_P5_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_P5_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_P5_ISR */


#ifdef EE_CORTEX_MX_GPIO_P6_ISR
#ifdef EE_CORTEX_MX_GPIO_P6_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_P6_INT_NUM, EE_CORTEX_MX_GPIO_P6_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_P6_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_P6_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_P6_ISR */


#ifdef EE_CORTEX_MX_GPIO_P7_ISR
#ifdef EE_CORTEX_MX_GPIO_P7_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_P7_INT_NUM, EE_CORTEX_MX_GPIO_P7_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_P7_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_P7_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_P7_ISR */


#ifdef EE_CORTEX_MX_GPIO_Q0_ISR
#ifdef EE_CORTEX_MX_GPIO_Q0_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_Q0_INT_NUM, EE_CORTEX_MX_GPIO_Q0_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_Q0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_Q0_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_Q0_ISR */


#ifdef EE_CORTEX_MX_GPIO_Q1_ISR
#ifdef EE_CORTEX_MX_GPIO_Q1_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_Q1_INT_NUM, EE_CORTEX_MX_GPIO_Q1_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_Q1_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_Q1_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_Q1_ISR */


#ifdef EE_CORTEX_MX_GPIO_Q2_ISR
#ifdef EE_CORTEX_MX_GPIO_Q2_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_Q2_INT_NUM, EE_CORTEX_MX_GPIO_Q2_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_Q2_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_Q2_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_Q2_ISR */


#ifdef EE_CORTEX_MX_GPIO_Q3_ISR
#ifdef EE_CORTEX_MX_GPIO_Q3_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_Q3_INT_NUM, EE_CORTEX_MX_GPIO_Q3_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_Q3_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_Q3_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_Q3_ISR */


#ifdef EE_CORTEX_MX_GPIO_Q4_ISR
#ifdef EE_CORTEX_MX_GPIO_Q4_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_Q4_INT_NUM, EE_CORTEX_MX_GPIO_Q4_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_Q4_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_Q4_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_Q4_ISR */


#ifdef EE_CORTEX_MX_GPIO_Q5_ISR
#ifdef EE_CORTEX_MX_GPIO_Q5_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_Q5_INT_NUM, EE_CORTEX_MX_GPIO_Q5_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_Q5_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_Q5_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_Q5_ISR */


#ifdef EE_CORTEX_MX_GPIO_Q6_ISR
#ifdef EE_CORTEX_MX_GPIO_Q6_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_Q6_INT_NUM, EE_CORTEX_MX_GPIO_Q6_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_Q6_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_Q6_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_Q6_ISR */


#ifdef EE_CORTEX_MX_GPIO_Q7_ISR
#ifdef EE_CORTEX_MX_GPIO_Q7_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_Q7_INT_NUM, EE_CORTEX_MX_GPIO_Q7_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_Q7_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_Q7_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_Q7_ISR */


#ifdef EE_CORTEX_MX_GPIO_R_ISR
#ifdef EE_CORTEX_MX_GPIO_R_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_R_INT_NUM, EE_CORTEX_MX_GPIO_R_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_R_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_R_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_R_ISR */


#ifdef EE_CORTEX_MX_GPIO_S_ISR
#ifdef EE_CORTEX_MX_GPIO_S_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_GPIO_S_INT_NUM, EE_CORTEX_MX_GPIO_S_ISR_PRI);
#endif	/* EE_CORTEX_MX_GPIO_S_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_GPIO_S_INT_NUM);
#endif	/* EE_CORTEX_MX_GPIO_S_ISR */


#ifdef EE_CORTEX_MX_UART_0_ISR
#ifdef EE_CORTEX_MX_UART_0_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_UART_0_INT_NUM, EE_CORTEX_MX_UART_0_ISR_PRI);
#endif	/* EE_CORTEX_MX_UART_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_UART_0_INT_NUM);
#endif	/* EE_CORTEX_MX_UART_0_ISR */


#ifdef EE_CORTEX_MX_UART_1_ISR
#ifdef EE_CORTEX_MX_UART_1_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_UART_1_INT_NUM, EE_CORTEX_MX_UART_1_ISR_PRI);
#endif	/* EE_CORTEX_MX_UART_1_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_UART_1_INT_NUM);
#endif	/* EE_CORTEX_MX_UART_1_ISR */


#ifdef EE_CORTEX_MX_UART_2_ISR
#ifdef EE_CORTEX_MX_UART_2_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_UART_2_INT_NUM, EE_CORTEX_MX_UART_2_ISR_PRI);
#endif	/* EE_CORTEX_MX_UART_2_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_UART_2_INT_NUM);
#endif	/* EE_CORTEX_MX_UART_2_ISR */


#ifdef EE_CORTEX_MX_UART_3_ISR
#ifdef EE_CORTEX_MX_UART_3_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_UART_3_INT_NUM, EE_CORTEX_MX_UART_3_ISR_PRI);
#endif	/* EE_CORTEX_MX_UART_3_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_UART_3_INT_NUM);
#endif	/* EE_CORTEX_MX_UART_3_ISR */


#ifdef EE_CORTEX_MX_UART_4_ISR
#ifdef EE_CORTEX_MX_UART_4_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_UART_4_INT_NUM, EE_CORTEX_MX_UART_4_ISR_PRI);
#endif	/* EE_CORTEX_MX_UART_4_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_UART_4_INT_NUM);
#endif	/* EE_CORTEX_MX_UART_4_ISR */


#ifdef EE_CORTEX_MX_UART_5_ISR
#ifdef EE_CORTEX_MX_UART_5_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_UART_5_INT_NUM, EE_CORTEX_MX_UART_5_ISR_PRI);
#endif	/* EE_CORTEX_MX_UART_5_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_UART_5_INT_NUM);
#endif	/* EE_CORTEX_MX_UART_5_ISR */


#ifdef EE_CORTEX_MX_UART_6_ISR
#ifdef EE_CORTEX_MX_UART_6_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_UART_6_INT_NUM, EE_CORTEX_MX_UART_6_ISR_PRI);
#endif	/* EE_CORTEX_MX_UART_6_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_UART_6_INT_NUM);
#endif	/* EE_CORTEX_MX_UART_6_ISR */


#ifdef EE_CORTEX_MX_UART_7_ISR
#ifdef EE_CORTEX_MX_UART_7_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_UART_7_INT_NUM, EE_CORTEX_MX_UART_7_ISR_PRI);
#endif	/* EE_CORTEX_MX_UART_7_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_UART_7_INT_NUM);
#endif	/* EE_CORTEX_MX_UART_7_ISR */


#ifdef EE_CORTEX_MX_SSI_0_ISR
#ifdef EE_CORTEX_MX_SSI_0_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_SSI_0_INT_NUM, EE_CORTEX_MX_SSI_0_ISR_PRI);
#endif	/* EE_CORTEX_MX_SSI_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_SSI_0_INT_NUM);
#endif	/* EE_CORTEX_MX_SSI_0_ISR */


#ifdef EE_CORTEX_MX_SSI_1_ISR
#ifdef EE_CORTEX_MX_SSI_1_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_SSI_1_INT_NUM, EE_CORTEX_MX_SSI_1_ISR_PRI);
#endif	/* EE_CORTEX_MX_SSI_1_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_SSI_1_INT_NUM);
#endif	/* EE_CORTEX_MX_SSI_1_ISR */


#ifdef EE_CORTEX_MX_SSI_2_ISR
#ifdef EE_CORTEX_MX_SSI_2_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_SSI_2_INT_NUM, EE_CORTEX_MX_SSI_2_ISR_PRI);
#endif	/* EE_CORTEX_MX_SSI_2_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_SSI_2_INT_NUM);
#endif	/* EE_CORTEX_MX_SSI_2_ISR */


#ifdef EE_CORTEX_MX_SSI_3_ISR
#ifdef EE_CORTEX_MX_SSI_3_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_SSI_3_INT_NUM, EE_CORTEX_MX_SSI_3_ISR_PRI);
#endif	/* EE_CORTEX_MX_SSI_3_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_SSI_3_INT_NUM);
#endif	/* EE_CORTEX_MX_SSI_3_ISR */


#ifdef EE_CORTEX_MX_I2C_0_ISR
#ifdef EE_CORTEX_MX_I2C_0_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_I2C_0_INT_NUM, EE_CORTEX_MX_I2C_0_ISR_PRI);
#endif	/* EE_CORTEX_MX_I2C_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_I2C_0_INT_NUM);
#endif	/* EE_CORTEX_MX_I2C_0_ISR */


#ifdef EE_CORTEX_MX_I2C_1_ISR
#ifdef EE_CORTEX_MX_I2C_1_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_I2C_1_INT_NUM, EE_CORTEX_MX_I2C_1_ISR_PRI);
#endif	/* EE_CORTEX_MX_I2C_1_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_I2C_1_INT_NUM);
#endif	/* EE_CORTEX_MX_I2C_1_ISR */


#ifdef EE_CORTEX_MX_I2C_2_ISR
#ifdef EE_CORTEX_MX_I2C_2_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_I2C_2_INT_NUM, EE_CORTEX_MX_I2C_2_ISR_PRI);
#endif	/* EE_CORTEX_MX_I2C_2_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_I2C_2_INT_NUM);
#endif	/* EE_CORTEX_MX_I2C_2_ISR */


#ifdef EE_CORTEX_MX_I2C_3_ISR
#ifdef EE_CORTEX_MX_I2C_3_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_I2C_3_INT_NUM, EE_CORTEX_MX_I2C_3_ISR_PRI);
#endif	/* EE_CORTEX_MX_I2C_3_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_I2C_3_INT_NUM);
#endif	/* EE_CORTEX_MX_I2C_3_ISR */


#ifdef EE_CORTEX_MX_I2C_4_ISR
#ifdef EE_CORTEX_MX_I2C_4_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_I2C_4_INT_NUM, EE_CORTEX_MX_I2C_4_ISR_PRI);
#endif	/* EE_CORTEX_MX_I2C_4_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_I2C_4_INT_NUM);
#endif	/* EE_CORTEX_MX_I2C_4_ISR */


#ifdef EE_CORTEX_MX_I2C_5_ISR
#ifdef EE_CORTEX_MX_I2C_5_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_I2C_5_INT_NUM, EE_CORTEX_MX_I2C_5_ISR_PRI);
#endif	/* EE_CORTEX_MX_I2C_5_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_I2C_5_INT_NUM);
#endif	/* EE_CORTEX_MX_I2C_5_ISR */


#ifdef EE_CORTEX_MX_PWM_0_FAULT_ISR
#ifdef EE_CORTEX_MX_PWM_0_FAULT_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_PWM_0_FAULT_INT_NUM, EE_CORTEX_MX_PWM_0_FAULT_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_PWM_0_FAULT_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_PWM_0_FAULT_INT_NUM);
#endif	/* EE_CORTEX_MX_PWM_0_FAULT_ISR */


#ifdef EE_CORTEX_MX_PWM_0_0_ISR
#ifdef EE_CORTEX_MX_PWM_0_0_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_PWM_0_0_INT_NUM, EE_CORTEX_MX_PWM_0_0_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_PWM_0_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_PWM_0_0_INT_NUM);
#endif	/* EE_CORTEX_MX_PWM_0_0_ISR */


#ifdef EE_CORTEX_MX_PWM_0_1_ISR
#ifdef EE_CORTEX_MX_PWM_0_1_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_PWM_0_1_INT_NUM, EE_CORTEX_MX_PWM_0_1_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_PWM_0_1_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_PWM_0_1_INT_NUM);
#endif	/* EE_CORTEX_MX_PWM_0_1_ISR */


#ifdef EE_CORTEX_MX_PWM_0_2_ISR
#ifdef EE_CORTEX_MX_PWM_0_2_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_PWM_0_2_INT_NUM, EE_CORTEX_MX_PWM_0_2_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_PWM_0_2_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_PWM_0_2_INT_NUM);
#endif	/* EE_CORTEX_MX_PWM_0_2_ISR */


#ifdef EE_CORTEX_MX_PWM_0_3_ISR
#ifdef EE_CORTEX_MX_PWM_0_3_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_PWM_0_3_INT_NUM, EE_CORTEX_MX_PWM_0_3_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_PWM_0_3_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_PWM_0_3_INT_NUM);
#endif	/* EE_CORTEX_MX_PWM_0_3_ISR */


#ifdef EE_CORTEX_MX_PWM_1_FAULT_ISR
#ifdef EE_CORTEX_MX_PWM_1_FAULT_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_PWM_1_FAULT_INT_NUM, EE_CORTEX_MX_PWM_1_FAULT_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_PWM_1_FAULT_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_PWM_1_FAULT_INT_NUM);
#endif	/* EE_CORTEX_MX_PWM_1_FAULT_ISR */


#ifdef EE_CORTEX_MX_PWM_1_0_ISR
#ifdef EE_CORTEX_MX_PWM_1_0_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_PWM_1_0_INT_NUM, EE_CORTEX_MX_PWM_1_0_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_PWM_1_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_PWM_1_0_INT_NUM);
#endif	/* EE_CORTEX_MX_PWM_1_0_ISR */


#ifdef EE_CORTEX_MX_PWM_1_1_ISR
#ifdef EE_CORTEX_MX_PWM_1_1_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_PWM_1_1_INT_NUM, EE_CORTEX_MX_PWM_1_1_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_PWM_1_1_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_PWM_1_1_INT_NUM);
#endif	/* EE_CORTEX_MX_PWM_1_1_ISR */


#ifdef EE_CORTEX_MX_PWM_1_2_ISR
#ifdef EE_CORTEX_MX_PWM_1_2_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_PWM_1_2_INT_NUM, EE_CORTEX_MX_PWM_1_2_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_PWM_1_2_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_PWM_1_2_INT_NUM);
#endif	/* EE_CORTEX_MX_PWM_1_2_ISR */


#ifdef EE_CORTEX_MX_PWM_1_3_ISR
#ifdef EE_CORTEX_MX_PWM_1_3_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_PWM_1_3_INT_NUM, EE_CORTEX_MX_PWM_1_3_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_PWM_1_3_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_PWM_1_3_INT_NUM);
#endif	/* EE_CORTEX_MX_PWM_1_3_ISR */


#ifdef EE_CORTEX_MX_QUAD_ENC_0_ISR
#ifdef EE_CORTEX_MX_QUAD_ENC_0_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_QUAD_ENC_0_INT_NUM, EE_CORTEX_MX_QUAD_ENC_0_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_QUAD_ENC_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_QUAD_ENC_0_INT_NUM);
#endif	/* EE_CORTEX_MX_QUAD_ENC_0_ISR */


#ifdef EE_CORTEX_MX_QUAD_ENC_1_ISR
#ifdef EE_CORTEX_MX_QUAD_ENC_1_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_QUAD_ENC_1_INT_NUM, EE_CORTEX_MX_QUAD_ENC_1_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_QUAD_ENC_1_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_QUAD_ENC_1_INT_NUM);
#endif	/* EE_CORTEX_MX_QUAD_ENC_1_ISR */


#ifdef EE_CORTEX_MX_QUAD_ENC_2_ISR
#ifdef EE_CORTEX_MX_QUAD_ENC_2_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_QUAD_ENC_2_INT_NUM, EE_CORTEX_MX_QUAD_ENC_2_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_QUAD_ENC_2_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_QUAD_ENC_2_INT_NUM);
#endif	/* EE_CORTEX_MX_QUAD_ENC_2_ISR */


#ifdef EE_CORTEX_MX_ADC_0_0_ISR
#ifdef EE_CORTEX_MX_ADC_0_0_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_ADC_0_0_INT_NUM, EE_CORTEX_MX_ADC_0_0_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_ADC_0_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_ADC_0_0_INT_NUM);
#endif	/* EE_CORTEX_MX_ADC_0_0_ISR */


#ifdef EE_CORTEX_MX_ADC_0_1_ISR
#ifdef EE_CORTEX_MX_ADC_0_1_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_ADC_0_1_INT_NUM, EE_CORTEX_MX_ADC_0_1_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_ADC_0_1_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_ADC_0_1_INT_NUM);
#endif	/* EE_CORTEX_MX_ADC_0_1_ISR */


#ifdef EE_CORTEX_MX_ADC_0_2_ISR
#ifdef EE_CORTEX_MX_ADC_0_2_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_ADC_0_2_INT_NUM, EE_CORTEX_MX_ADC_0_2_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_ADC_0_2_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_ADC_0_2_INT_NUM);
#endif	/* EE_CORTEX_MX_ADC_0_2_ISR */


#ifdef EE_CORTEX_MX_ADC_0_3_ISR
#ifdef EE_CORTEX_MX_ADC_0_3_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_ADC_0_3_INT_NUM, EE_CORTEX_MX_ADC_0_3_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_ADC_0_3_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_ADC_0_3_INT_NUM);
#endif	/* EE_CORTEX_MX_ADC_0_3_ISR */


#ifdef EE_CORTEX_MX_ADC_1_0_ISR
#ifdef EE_CORTEX_MX_ADC_1_0_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_ADC_1_0_INT_NUM, EE_CORTEX_MX_ADC_1_0_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_ADC_1_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_ADC_1_0_INT_NUM);
#endif	/* EE_CORTEX_MX_ADC_1_0_ISR */


#ifdef EE_CORTEX_MX_ADC_1_1_ISR
#ifdef EE_CORTEX_MX_ADC_1_1_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_ADC_1_1_INT_NUM, EE_CORTEX_MX_ADC_1_1_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_ADC_1_1_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_ADC_1_1_INT_NUM);
#endif	/* EE_CORTEX_MX_ADC_1_1_ISR */


#ifdef EE_CORTEX_MX_ADC_1_2_ISR
#ifdef EE_CORTEX_MX_ADC_1_2_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_ADC_1_2_INT_NUM, EE_CORTEX_MX_ADC_1_2_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_ADC_1_2_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_ADC_1_2_INT_NUM);
#endif	/* EE_CORTEX_MX_ADC_1_2_ISR */


#ifdef EE_CORTEX_MX_ADC_1_3_ISR
#ifdef EE_CORTEX_MX_ADC_1_3_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_ADC_1_3_INT_NUM, EE_CORTEX_MX_ADC_1_3_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_ADC_1_3_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_ADC_1_3_INT_NUM);
#endif	/* EE_CORTEX_MX_ADC_1_3_ISR */


#ifdef EE_CORTEX_MX_TIMER_0_A_ISR
#ifdef EE_CORTEX_MX_TIMER_0_A_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_TIMER_0_A_INT_NUM, EE_CORTEX_MX_TIMER_0_A_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_TIMER_0_A_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_TIMER_0_A_INT_NUM);
#endif	/* EE_CORTEX_MX_TIMER_0_A_ISR */


#ifdef EE_CORTEX_MX_TIMER_0_B_ISR
#ifdef EE_CORTEX_MX_TIMER_0_B_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_TIMER_0_B_INT_NUM, EE_CORTEX_MX_TIMER_0_B_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_TIMER_0_B_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_TIMER_0_B_INT_NUM);
#endif	/* EE_CORTEX_MX_TIMER_0_B_ISR */

#ifdef EE_CORTEX_MX_TIMER_1_A_ISR
#ifdef EE_CORTEX_MX_TIMER_1_A_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_TIMER_1_A_INT_NUM, EE_CORTEX_MX_TIMER_1_A_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_TIMER_1_A_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_TIMER_1_A_INT_NUM);
#endif	/* EE_CORTEX_MX_TIMER_1_A_ISR */


#ifdef EE_CORTEX_MX_TIMER_1_B_ISR
#ifdef EE_CORTEX_MX_TIMER_1_B_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_TIMER_1_B_INT_NUM, EE_CORTEX_MX_TIMER_1_B_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_TIMER_1_B_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_TIMER_1_B_INT_NUM);
#endif	/* EE_CORTEX_MX_TIMER_1_B_ISR */


#ifdef EE_CORTEX_MX_TIMER_2_A_ISR
#ifdef EE_CORTEX_MX_TIMER_2_A_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_TIMER_2_A_INT_NUM, EE_CORTEX_MX_TIMER_2_A_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_TIMER_2_A_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_TIMER_2_A_INT_NUM);
#endif	/* EE_CORTEX_MX_TIMER_2_A_ISR */


#ifdef EE_CORTEX_MX_TIMER_2_B_ISR
#ifdef EE_CORTEX_MX_TIMER_2_B_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_TIMER_2_B_INT_NUM, EE_CORTEX_MX_TIMER_2_B_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_TIMER_2_B_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_TIMER_2_B_INT_NUM);
#endif	/* EE_CORTEX_MX_TIMER_2_B_ISR */


#ifdef EE_CORTEX_MX_TIMER_3_A_ISR
#ifdef EE_CORTEX_MX_TIMER_3_A_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_TIMER_3_A_INT_NUM, EE_CORTEX_MX_TIMER_3_A_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_TIMER_3_A_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_TIMER_3_A_INT_NUM);
#endif	/* EE_CORTEX_MX_TIMER_3_A_ISR */


#ifdef EE_CORTEX_MX_TIMER_3_B_ISR
#ifdef EE_CORTEX_MX_TIMER_3_B_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_TIMER_3_B_INT_NUM, EE_CORTEX_MX_TIMER_3_B_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_TIMER_3_B_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_TIMER_3_B_INT_NUM);
#endif	/* EE_CORTEX_MX_TIMER_3_B_ISR */


#ifdef EE_CORTEX_MX_TIMER_4_A_ISR
#ifdef EE_CORTEX_MX_TIMER_4_A_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_TIMER_4_A_INT_NUM, EE_CORTEX_MX_TIMER_4_A_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_TIMER_4_A_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_TIMER_4_A_INT_NUM);
#endif	/* EE_CORTEX_MX_TIMER_4_A_ISR */


#ifdef EE_CORTEX_MX_TIMER_4_B_ISR
#ifdef EE_CORTEX_MX_TIMER_4_B_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_TIMER_4_B_INT_NUM, EE_CORTEX_MX_TIMER_4_B_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_TIMER_4_B_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_TIMER_4_B_INT_NUM);
#endif	/* EE_CORTEX_MX_TIMER_4_B_ISR */


#ifdef EE_CORTEX_MX_TIMER_5_A_ISR
#ifdef EE_CORTEX_MX_TIMER_5_A_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_TIMER_5_A_INT_NUM, EE_CORTEX_MX_TIMER_5_A_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_TIMER_5_A_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_TIMER_5_A_INT_NUM);
#endif	/* EE_CORTEX_MX_TIMER_5_A_ISR */


#ifdef EE_CORTEX_MX_TIMER_5_B_ISR
#ifdef EE_CORTEX_MX_TIMER_5_B_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_TIMER_5_B_INT_NUM, EE_CORTEX_MX_TIMER_5_B_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_TIMER_5_B_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_TIMER_5_B_INT_NUM);
#endif	/* EE_CORTEX_MX_TIMER_5_B_ISR */


#ifdef EE_CORTEX_MX_WIDE_TIMER_0_A_ISR
#ifdef EE_CORTEX_MX_WIDE_TIMER_0_A_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_WIDE_TIMER_0_A_INT_NUM,
	  EE_CORTEX_MX_WIDE_TIMER_0_A_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_0_A_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_WIDE_TIMER_0_A_INT_NUM);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_0_A_ISR */


#ifdef EE_CORTEX_MX_WIDE_TIMER_0_B_ISR
#ifdef EE_CORTEX_MX_WIDE_TIMER_0_B_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_WIDE_TIMER_0_B_INT_NUM,
	  EE_CORTEX_MX_WIDE_TIMER_0_B_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_0_B_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_WIDE_TIMER_0_B_INT_NUM);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_0_B_ISR */

#ifdef EE_CORTEX_MX_WIDE_TIMER_1_A_ISR
#ifdef EE_CORTEX_MX_WIDE_TIMER_1_A_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_WIDE_TIMER_1_A_INT_NUM,
	  EE_CORTEX_MX_WIDE_TIMER_1_A_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_1_A_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_WIDE_TIMER_1_A_INT_NUM);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_1_A_ISR */


#ifdef EE_CORTEX_MX_WIDE_TIMER_1_B_ISR
#ifdef EE_CORTEX_MX_WIDE_TIMER_1_B_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_WIDE_TIMER_1_B_INT_NUM,
	  EE_CORTEX_MX_WIDE_TIMER_1_B_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_1_B_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_WIDE_TIMER_1_B_INT_NUM);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_1_B_ISR */


#ifdef EE_CORTEX_MX_WIDE_TIMER_2_A_ISR
#ifdef EE_CORTEX_MX_WIDE_TIMER_2_A_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_WIDE_TIMER_2_A_INT_NUM,
	  EE_CORTEX_MX_WIDE_TIMER_2_A_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_2_A_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_WIDE_TIMER_2_A_INT_NUM);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_2_A_ISR */


#ifdef EE_CORTEX_MX_WIDE_TIMER_2_B_ISR
#ifdef EE_CORTEX_MX_WIDE_TIMER_2_B_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_WIDE_TIMER_2_B_INT_NUM,
	  EE_CORTEX_MX_WIDE_TIMER_2_B_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_2_B_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_WIDE_TIMER_2_B_INT_NUM);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_2_B_ISR */


#ifdef EE_CORTEX_MX_WIDE_TIMER_3_A_ISR
#ifdef EE_CORTEX_MX_WIDE_TIMER_3_A_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_WIDE_TIMER_3_A_INT_NUM,
	  EE_CORTEX_MX_WIDE_TIMER_3_A_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_3_A_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_WIDE_TIMER_3_A_INT_NUM);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_3_A_ISR */


#ifdef EE_CORTEX_MX_WIDE_TIMER_3_B_ISR
#ifdef EE_CORTEX_MX_WIDE_TIMER_3_B_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_WIDE_TIMER_3_B_INT_NUM,
	  EE_CORTEX_MX_WIDE_TIMER_3_B_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_3_B_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_WIDE_TIMER_3_B_INT_NUM);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_3_B_ISR */


#ifdef EE_CORTEX_MX_WIDE_TIMER_4_A_ISR
#ifdef EE_CORTEX_MX_WIDE_TIMER_4_A_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_WIDE_TIMER_4_A_INT_NUM,
	  EE_CORTEX_MX_WIDE_TIMER_4_A_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_4_A_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_WIDE_TIMER_4_A_INT_NUM);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_4_A_ISR */


#ifdef EE_CORTEX_MX_WIDE_TIMER_4_B_ISR
#ifdef EE_CORTEX_MX_WIDE_TIMER_4_B_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_WIDE_TIMER_4_B_INT_NUM,
	  EE_CORTEX_MX_WIDE_TIMER_4_B_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_4_B_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_WIDE_TIMER_4_B_INT_NUM);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_4_B_ISR */


#ifdef EE_CORTEX_MX_WIDE_TIMER_5_A_ISR
#ifdef EE_CORTEX_MX_WIDE_TIMER_5_A_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_WIDE_TIMER_5_A_INT_NUM,
	  EE_CORTEX_MX_WIDE_TIMER_5_A_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_5_A_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_WIDE_TIMER_5_A_INT_NUM);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_5_A_ISR */


#ifdef EE_CORTEX_MX_WIDE_TIMER_5_B_ISR
#ifdef EE_CORTEX_MX_WIDE_TIMER_5_B_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_WIDE_TIMER_5_B_INT_NUM,
	  EE_CORTEX_MX_WIDE_TIMER_5_B_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_5_B_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_WIDE_TIMER_5_B_INT_NUM);
#endif	/* EE_CORTEX_MX_WIDE_TIMER_5_B_ISR */


#ifdef EE_CORTEX_MX_ANALOG_CMP_0_ISR
#ifdef EE_CORTEX_MX_ANALOG_CMP_0_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_ANALOG_CMP_0_INT_NUM, EE_CORTEX_MX_ANALOG_CMP_0_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_ANALOG_CMP_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_ANALOG_CMP_0_INT_NUM);
#endif	/* EE_CORTEX_MX_ANALOG_CMP_0_ISR */


#ifdef EE_CORTEX_MX_ANALOG_CMP_1_ISR
#ifdef EE_CORTEX_MX_ANALOG_CMP_1_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_ANALOG_CMP_1_INT_NUM, EE_CORTEX_MX_ANALOG_CMP_1_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_ANALOG_CMP_1_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_ANALOG_CMP_1_INT_NUM);
#endif	/* EE_CORTEX_MX_ANALOG_CMP_1_ISR */


#ifdef EE_CORTEX_MX_ANALOG_CMP_2_ISR
#ifdef EE_CORTEX_MX_ANALOG_CMP_2_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_ANALOG_CMP_2_INT_NUM, EE_CORTEX_MX_ANALOG_CMP_2_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_ANALOG_CMP_2_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_ANALOG_CMP_2_INT_NUM);
#endif	/* EE_CORTEX_MX_ANALOG_CMP_2_ISR */


#ifdef EE_CORTEX_MX_SYS_CTRL_ISR
#ifdef EE_CORTEX_MX_SYS_CTRL_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_SYS_CTRL_INT_NUM, EE_CORTEX_MX_SYS_CTRL_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_SYS_CTRL_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_SYS_CTRL_INT_NUM);
#endif	/* EE_CORTEX_MX_SYS_CTRL_ISR */


#ifdef EE_CORTEX_MX_FLASH_CTRL_ISR
#ifdef EE_CORTEX_MX_FLASH_CTRL_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_FLASH_CTRL_INT_NUM, EE_CORTEX_MX_FLASH_CTRL_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_FLASH_CTRL_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_FLASH_CTRL_INT_NUM);
#endif	/* EE_CORTEX_MX_FLASH_CTRL_ISR */


#ifdef EE_CORTEX_MX_CAN_0_ISR
#ifdef EE_CORTEX_MX_CAN_0_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_CAN_0_INT_NUM, EE_CORTEX_MX_CAN_0_ISR_PRI);
#endif	/* EE_CORTEX_MX_CAN_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_CAN_0_INT_NUM);
#endif	/* EE_CORTEX_MX_CAN_0_ISR */


#ifdef EE_CORTEX_MX_CAN_1_ISR
#ifdef EE_CORTEX_MX_CAN_1_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_CAN_1_INT_NUM, EE_CORTEX_MX_CAN_1_ISR_PRI);
#endif	/* EE_CORTEX_MX_CAN_1_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_CAN_1_INT_NUM);
#endif	/* EE_CORTEX_MX_CAN_1_ISR */


#ifdef EE_CORTEX_MX_CAN_2_ISR
#ifdef EE_CORTEX_MX_CAN_2_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_CAN_2_INT_NUM, EE_CORTEX_MX_CAN_2_ISR_PRI);
#endif	/* EE_CORTEX_MX_CAN_2_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_CAN_2_INT_NUM);
#endif	/* EE_CORTEX_MX_CAN_2_ISR */


#ifdef EE_CORTEX_MX_ETHERNET_ISR
#ifdef EE_CORTEX_MX_ETHERNET_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_ETHERNET_INT_NUM, EE_CORTEX_MX_ETHERNET_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_ETHERNET_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_ETHERNET_INT_NUM);
#endif	/* EE_CORTEX_MX_ETHERNET_ISR */

#ifdef EE_CORTEX_MX_HIBERNATE_ISR
#ifdef EE_CORTEX_MX_HIBERNATE_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_HIBERNATE_INT_NUM, EE_CORTEX_MX_HIBERNATE_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_HIBERNATE_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_HIBERNATE_INT_NUM);
#endif	/* EE_CORTEX_MX_HIBERNATE_ISR */

#ifdef EE_CORTEX_MX_USB_0_ISR
#ifdef EE_CORTEX_MX_USB_0_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_USB_0_INT_NUM, EE_CORTEX_MX_USB_0_ISR_PRI);
#endif	/* EE_CORTEX_MX_USB_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_USB_0_INT_NUM);
#endif	/* EE_CORTEX_MX_USB_0_ISR */

#ifdef EE_CORTEX_MX_UDMA_SOFT_TRANSF_ISR
#ifdef EE_CORTEX_MX_UDMA_SOFT_TRANSF_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_UDMA_SOFT_TRANSF_INT_NUM,
	  EE_CORTEX_MX_UDMA_SOFT_TRANSF_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_UDMA_SOFT_TRANSF_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_UDMA_SOFT_TRANSF_INT_NUM);
#endif	/* EE_CORTEX_MX_UDMA_SOFT_TRANSF_ISR */


#ifdef EE_CORTEX_MX_UDMA_ERR_ISR
#ifdef EE_CORTEX_MX_UDMA_ERR_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_UDMA_ERR_INT_NUM, EE_CORTEX_MX_UDMA_ERR_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_UDMA_ERR_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_UDMA_ERR_INT_NUM);
#endif	/* EE_CORTEX_MX_UDMA_ERR_ISR */


#ifdef EE_CORTEX_MX_I2S_0_ISR
#ifdef EE_CORTEX_MX_I2S_0_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_I2S_0_INT_NUM, EE_CORTEX_MX_I2S_0_ISR_PRI);
#endif	/* EE_CORTEX_MX_I2S_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_I2S_0_INT_NUM);
#endif	/* EE_CORTEX_MX_I2S_0_ISR */


#ifdef EE_CORTEX_MX_EXT_BUS_0_ISR
#ifdef EE_CORTEX_MX_EXT_BUS_0_ISR_PRI
	NVIC_SET_PRI(
	  EE_CORTEX_MX_EXT_BUS_0_INT_NUM, EE_CORTEX_MX_EXT_BUS_0_ISR_PRI
	);
#endif	/* EE_CORTEX_MX_EXT_BUS_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_EXT_BUS_0_INT_NUM);
#endif	/* EE_CORTEX_MX_EXT_BUS_0_ISR */


#ifdef EE_CORTEX_MX_FPU_ISR
#ifdef EE_CORTEX_MX_FPU_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_FPU_INT_NUM, EE_CORTEX_MX_FPU_ISR_PRI);
#endif	/* EE_CORTEX_MX_FPU_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_FPU_INT_NUM);
#endif	/* EE_CORTEX_MX_FPU_ISR */


#ifdef EE_CORTEX_MX_PECI_0_ISR
#ifdef EE_CORTEX_MX_PECI_0_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_PECI_0_INT_NUM, EE_CORTEX_MX_PECI_0_ISR_PRI);
#endif	/* EE_CORTEX_MX_PECI_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_PECI_0_INT_NUM);
#endif	/* EE_CORTEX_MX_PECI_0_ISR */


#ifdef EE_CORTEX_MX_LCP_0_ISR
#ifdef EE_CORTEX_MX_LCP_0_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_LCP_0_INT_NUM, EE_CORTEX_MX_LCP_0_ISR_PRI);
#endif	/* EE_CORTEX_MX_LCP_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_LCP_0_INT_NUM);
#endif	/* EE_CORTEX_MX_LCP_0_ISR */


#ifdef EE_CORTEX_MX_FAN_0_ISR
#ifdef EE_CORTEX_MX_FAN_0_ISR_PRI
	NVIC_SET_PRI(EE_CORTEX_MX_FAN_0_INT_NUM, EE_CORTEX_MX_FAN_0_ISR_PRI);
#endif	/* EE_CORTEX_MX_FAN_0_ISR_PRI */
	NVIC_INT_ENABLE(EE_CORTEX_MX_FAN_0_INT_NUM);
#endif	/* EE_CORTEX_MX_FAN_0_ISR */
}
