#!/bin/sh
# This script is needed to compile a distribution for Cortex M0.
# Execute it using ". ./filename" before to run compilation of testcases.

#If you need to set EEBASE, uncomment the following line changing the path accordingly the correct position of ee_files
#export EEBASE=/cygdrive/c/Evidence/eclipse/plugins/com.eu.evidence.ee_1.6.0.201106072202/ee_files

export ECLIPSE_HOME=C:/Evidence/eclipse